apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  config.yaml: |
    {{- range $key, $value := .Values.configMap }}
      {{ $key }}: {{ $value | quote }}
    {{- end -}}
